name: Build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  CI:
    name: Build and test on Erlang/OTP ${{ matrix.otp-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        otp-version: [23, 24, 25]
    env:
      LATEST_ERLANG_OTP: 25
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp-version}}
          elixir-version: '1.13'
      - name: Compile
        run: make
      - name: Test
        run: make tests
